---
name: Build Artifacts

on:
  push:
    branches: [ main ]
    paths-ignore: [ "*.md" ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ "*.md" ]

jobs:
  Compile-All:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4

      - name: Cache Vagrant boxes
        uses: actions/cache@v4.0.2
        with:
          path: ~/.vagrant.d/boxes
          key: $${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up & provision
        run: |
          vagrant plugin install vagrant-disksize
          vagrant up --provision
        env:
          VER: 23.05

      - name: Get Coverage Badge SVG
        run: make -B $(pwd)/images/coverage-badge.svg

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: GPG user
        run: |
          echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
          echo "username:    ${{ steps.import-gpg.outputs.name }}"
          echo "email:       ${{ steps.import-gpg.outputs.email }}"

      - name: Auto-commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: auto-commit of artifacts
          branch: main
          commit_options: '--no-verify --signoff -S'
          file_pattern: 'syntaxes/* images/*'
          commit_user_name: "${{ steps.import-gpg.outputs.name }}"
          commit_user_email: "${{ steps.import-gpg.outputs.email }}"

      - name: Run if changes have been detected
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "New TextMate grammar was published"
