---
name: "TextMate Grammar Coverage Badge"

on:
  push:
    branches: [ main ]
    paths: [ "src/**", "tests/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "src/**", "tests/**" ]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Install xsltproc
        run: sudo apt-get install -y xsltproc

      - uses: actions/checkout@v4

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Get SVG
        run: make -B $(pwd)/images/coverage-badge.svg

      - name: GPG user
        run: |
          echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
          echo "username:    ${{ steps.import-gpg.outputs.name }}"
          echo "email:       ${{ steps.import-gpg.outputs.email }}"

      - name: Auto-commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: auto-commit of updated coverage badge
          branch: main
          commit_options: '--no-verify --signoff -S'
          file_pattern: 'images/*'
          commit_user_name: "${{ steps.import-gpg.outputs.name }}"
          commit_user_email: "${{ steps.import-gpg.outputs.email }}"

      - name: Run if changes have been detected
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "New code coverage was published"
