---
name: pre-commit

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files }} --show-diff-on-failure
