---
name: pre-commit

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  Pre-commit:
    runs-on: macos-12
    steps:
      - name: Install pre-commit, jsonlint, and yamllint
        run: brew install pre-commit jsonlint yamllint

      - name: Checkout
        uses: actions/checkout@v3

      - id: file-changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ' '

      - name: Run pre-commit
        run: |
          pre-commit run --show-diff-on-failure\
                         --color=always\
                         --files ${{ steps.file-changes.outputs.files }}
        shell: bash

      - name: Show pre-commit logs
        if: failure()
        run: cat ~/.cache/pre-commit/pre-commit.log

      - name: Show pre-commit version
        run: pre-commit --version
